### ISSUE TITLE
debug commands on hdmi2usb

### ISSUE THREAD

**Issue by deeprave** [timvideos/HDMI2USB-firmware-prebuilt#3]
A feature request for the firmware to simplify and improve things a little:

Instead of the debug command being a toggle to the debug interface, be more deterministic and provide (even in addition to the toggle is ok):

debug [input]X [on|off]
  and
debug [input]X ?

returning the current debug state for the selected channel, where X is 1 or 2.

In addition, missing value  of 'X' should affect all available channels, and return status of all channels in the second case.  e.g. "debug on" or "debug input on" should enable debug on all channels.

**Comment by mithro** [comment]
This issue was moved to timvideos/HDMI2USB-misoc-firmware#213
